//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project_back_end
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book_info()
        {
            this.comment = new HashSet<comment>();
            this.score1 = new HashSet<score>();
            this.user_book = new HashSet<user_book>();
        }
    
        public int id { get; set; }
        public string book_name { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public string translator { get; set; }
        public string publish_date { get; set; }
        public Nullable<int> page_num { get; set; }
        public string isbn { get; set; }
        public Nullable<float> score { get; set; }
        public Nullable<int> rating_num { get; set; }
        public string book_image { get; set; }
        public string introduction { get; set; }
        public string tags { get; set; }
        public string author_info { get; set; }
        public string producer { get; set; }
        public string original_name { get; set; }
        public string binding { get; set; }
        public string subtitle { get; set; }
        public string series { get; set; }
        public Nullable<float> star1 { get; set; }
        public Nullable<float> star2 { get; set; }
        public Nullable<float> star3 { get; set; }
        public Nullable<float> star4 { get; set; }
        public Nullable<float> star5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<score> score1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_book> user_book { get; set; }
    }
}
