//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project_back_end
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class comment
    {
        public int commentid { get; set; }
        public Nullable<int> bookid { get; set; }
        public string username { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> commenttime { get; set; }

        [JsonIgnore]
        public virtual book_info book_info { get; set; }
        [JsonIgnore]
        public virtual user user { get; set; }
    }
}
