//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project_back_end
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookEntities : DbContext
    {
        public bookEntities()
            : base("name=bookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book_info> book_info { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<score> score { get; set; }
        public virtual DbSet<tag_info> tag_info { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_book> user_book { get; set; }
    }
}
