//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project_back_end
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public string username { get; set; }
        public int bookid { get; set; }
        public Nullable<int> score1 { get; set; }
    
        public virtual book_info book_info { get; set; }
        public virtual user user { get; set; }
    }
}
